import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Simple compatibility names (matches main branch expectations)
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
        accent: 'var(--accent)',
        background: 'var(--background)',
        surface: 'var(--surface)',
        text: 'var(--text)',
        'text-muted': 'var(--text-muted)',

        // Semantic design system colors (comprehensive token system)
        semantic: {
          primary: {
            DEFAULT: 'var(--color-primary)',
            hover: 'var(--color-primary-hover)',
            active: 'var(--color-primary-active)',
            subtle: 'var(--color-primary-subtle)',
            muted: 'var(--color-primary-muted)',
          },
          secondary: {
            DEFAULT: 'var(--color-secondary)',
            hover: 'var(--color-secondary-hover)',
            active: 'var(--color-secondary-active)',
            subtle: 'var(--color-secondary-subtle)',
            muted: 'var(--color-secondary-muted)',
          },
          accent: {
            DEFAULT: 'var(--color-accent)',
            hover: 'var(--color-accent-hover)',
            active: 'var(--color-accent-active)',
            subtle: 'var(--color-accent-subtle)',
            muted: 'var(--color-accent-muted)',
          },
          background: {
            DEFAULT: 'var(--color-background)',
            subtle: 'var(--color-background-subtle)',
            muted: 'var(--color-background-muted)',
          },
          surface: {
            DEFAULT: 'var(--color-surface)',
            subtle: 'var(--color-surface-subtle)',
            muted: 'var(--color-surface-muted)',
            hover: 'var(--color-surface-hover)',
            active: 'var(--color-surface-active)',
          },
          text: {
            DEFAULT: 'var(--color-text)',
            subtle: 'var(--color-text-subtle)',
            muted: 'var(--color-text-muted)',
            disabled: 'var(--color-text-disabled)',
            placeholder: 'var(--color-text-placeholder)',
            inverse: 'var(--color-text-inverse)',
          },
          border: {
            DEFAULT: 'var(--color-border)',
            subtle: 'var(--color-border-subtle)',
            muted: 'var(--color-border-muted)',
            strong: 'var(--color-border-strong)',
          },
          success: {
            DEFAULT: 'var(--color-success)',
            subtle: 'var(--color-success-subtle)',
            muted: 'var(--color-success-muted)',
          },
          warning: {
            DEFAULT: 'var(--color-warning)',
            subtle: 'var(--color-warning-subtle)',
            muted: 'var(--color-warning-muted)',
          },
          error: {
            DEFAULT: 'var(--color-error)',
            subtle: 'var(--color-error-subtle)',
            muted: 'var(--color-error-muted)',
          },
          focus: 'var(--color-focus)',
        },
      },
      fontFamily: {
        sans: 'var(--font-family-sans)',
        serif: 'var(--font-family-serif)',
        mono: 'var(--font-family-mono)',
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        '6xl': 'var(--font-size-6xl)',
        '7xl': 'var(--font-size-7xl)',
        '8xl': 'var(--font-size-8xl)',
        '9xl': 'var(--font-size-9xl)',
      },
      lineHeight: {
        none: 'var(--line-height-none)',
        tight: 'var(--line-height-tight)',
        snug: 'var(--line-height-snug)',
        normal: 'var(--line-height-normal)',
        relaxed: 'var(--line-height-relaxed)',
        loose: 'var(--line-height-loose)',
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        extralight: 'var(--font-weight-extralight)',
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
        black: 'var(--font-weight-black)',
      },
      letterSpacing: {
        tighter: 'var(--letter-spacing-tighter)',
        tight: 'var(--letter-spacing-tight)',
        normal: 'var(--letter-spacing-normal)',
        wide: 'var(--letter-spacing-wide)',
        wider: 'var(--letter-spacing-wider)',
        widest: 'var(--letter-spacing-widest)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
        40: 'var(--space-40)',
        48: 'var(--space-48)',
        56: 'var(--space-56)',
        64: 'var(--space-64)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-base)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
      },
      zIndex: {
        hide: 'var(--z-index-hide)',
        auto: 'var(--z-index-auto)',
        base: 'var(--z-index-base)',
        docked: 'var(--z-index-docked)',
        dropdown: 'var(--z-index-dropdown)',
        sticky: 'var(--z-index-sticky)',
        banner: 'var(--z-index-banner)',
        overlay: 'var(--z-index-overlay)',
        modal: 'var(--z-index-modal)',
        popover: 'var(--z-index-popover)',
        skiplink: 'var(--z-index-skiplink)',
        toast: 'var(--z-index-toast)',
        tooltip: 'var(--z-index-tooltip)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        linear: 'var(--ease-linear)',
        in: 'var(--ease-in)',
        out: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        'back-in': 'var(--ease-back-in)',
        'back-out': 'var(--ease-back-out)',
        'back-in-out': 'var(--ease-back-in-out)',
      },
      blur: {
        none: 'var(--blur-none)',
        sm: 'var(--blur-sm)',
        DEFAULT: 'var(--blur-base)',
        md: 'var(--blur-md)',
        lg: 'var(--blur-lg)',
        xl: 'var(--blur-xl)',
        '2xl': 'var(--blur-2xl)',
        '3xl': 'var(--blur-3xl)',
      },
      animation: {
        'fade-in': 'fadeIn var(--duration-slow) var(--ease-out)',
        'slide-up': 'slideUp var(--duration-slow) var(--ease-out)',
        'slide-down': 'slideDown var(--duration-slow) var(--ease-out)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config

export default config
